#import required
import turtle
car=turtle.Turtle()
# For the rectangular body of the car
car.color("blue")
car.fillcolor("blue")
car.penup()
car.goto(0,0)
car.pendown()
car.begin_fill()
car.forward(370)
car.left(90)
car.forward(50)
car.left(90)
car.forward(370)
car.left(90)
car.forward(50)
car.end_fill()

#For the window and roof of the car
car.penup()
car.goto(100,50)
car.pendown()
car.setheading(45)
car.forward(70)
car.setheading(0)
car.forward(100)
car.setheading(-45)
car.forward(70)
car.setheading(90)
car.penup()
car.goto(200,50)
car.pendown()
car.forward(49)

# For the wheels of the car
car.penup()
car.goto(100,-10)
car.pendown()
car.color("black")
car.fillcolor("black")
car.begin_fill()
car.circle(20)
car.end_fill()
car.penup()
car.goto(300,-10)
car.pendown()
car.color("black")
car.fillcolor("black")
car.begin_fill()
car.circle(20)
car.end_fill()
car.hideturtle()